name: dart_vn2000
description: VN2000 converter for dart
version: 1.0.2
homepage: https://github.com/ankiimation/dart_vn2000

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  proj4dart: ^2.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
